In [4]:
import numpy as np
from datasets import load_dataset
import re, unidecode, string, random

dataset = load_dataset("aeslc")

Using custom data configuration default
Reusing dataset aeslc (/home/tibz/.cache/huggingface/datasets/aeslc/default/1.0.0/0f335d7ea7f9ab9e325673a86c6aa0e2cd503c5dbf17d48fddcb02840a92fc96)


In [5]:
corpus = []
for line in dataset['train']:
    corpus.append(line['email_body'])

corpus = " ".join(corpus)
corpus = re.sub(' +', ' ', re.sub('[^a-z ]', ' ', unidecode.unidecode(corpus).lower()))

In [6]:
PT = np.full((27,27), 0)
charset = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',' ']

corpus_size = 1000
corpus = corpus[0:corpus_size]

for char in charset:
    for next_char in charset:
        pair = char + next_char
        # detection du nombre de pairs
        pairs_found = sum(1 for i in range(len(corpus)) if corpus.startswith(pair, i))
        PT[charset.index(char), charset.index(next_char)] += pairs_found

# for i in range(len(charset)):
#     print(charset[i] + " : " + charset[np.argmax(PT[i,:])])

In [7]:
PT = PT / (corpus_size - 1)

email_size = 50
email = random.choice(charset[:26])

for char in range(email_size):
    email.index()
    email += "a"
    print(email)

TypeError: index() takes at least 1 argument (0 given)

In [9]:
PT.shape

(27, 27)

In [28]:

def generate_work(nb_letter):
    first_letter = random.choice(charset[:26])
    word = [charset.index(first_letter)]
    idx_first = charset.index(first_letter)

    for i in range(nb_letter-1):

        line_first = PT[idx_first,:]
        idx_second = np.argmax(line_first)
        word.append(idx_second)
        idx_first = idx_second

    w = ""
    for idx in word:
        w += charset[idx]
    return w

generate_work(9)

'xe t t t '

In [44]:
import matplotlib as plt
import numpy as np

 

list_hist = []
for i in range(100):
    list_y = []
    y = np.random.normal(loc=5,scale=3,size=1000)
    list_y.append(y)
    x, _ = np.histogram(list_y)
    print(x)

#plt.pyplot.plot(moyenne)

[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0

In [37]:
import seaborn

seaborn.lineplot(np.linspace(0, len(moyenne)),moyenne)

ValueError: arrays must all be same length